import{createClient}from'https://esm.sh/@supabase/supabase-js@2';
const supabase=createClient('https://vtnucevhyhfvymppjbfa.supabase.co','sb_publishable_-5iiF1Qgq--BKgXLHREINA_nPC7yVVY',{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id);
const money=i=>i.price?new Intl.NumberFormat('uk-UA',{maximumFractionDigits:0}).format(i.price)+' '+({USD:'$',EUR:'€',UAH:'₴'}[i.currency]||'$'):'Ціна уточнюється';
const leadLabels={new:'Нова',contacted:'Зв’язались',viewing:'Перегляд',negotiation:'Переговори',won:'Успішно',lost:'Втрачено'};
let leads=[],leadFilter='all';
function card(i,mode){const d=document.createElement('article');d.className='card';d.innerHTML=`${i.cover_photo_url?`<img src="${i.cover_photo_url}" alt="">`:'<div class="placeholder">⌂</div>'}<div class="card-body"><h3>${i.title||i.location_name||'Будинок'}</h3><p>${i.location_name||''}${i.address?' · '+i.address:''}</p><div class="price">${money(i)}</div><div class="card-actions"><a href="./?unit=${i.id}">Відкрити</a>${mode==='favorite'?`<button data-remove="${i.id}">Видалити</button>`:'<span class="badge">Підтверджено</span>'}</div>${mode==='seller'?`<form class="seller-edit"><label>Ціна<input name="price" type="number" min="0" value="${i.price||0}"></label><label>Статус<select name="status"><option value="available">У продажу</option><option value="reserved">Резерв</option><option value="sold">Продано</option><option value="inactive">Неактивне</option></select></label><label>Доступно<input name="count" type="number" min="0" value="${i.available_count||0}"></label><button>Зберегти</button><span class="save-status"></span></form>`:''}</div>`;if(mode==='seller'){d.querySelector('[name=status]').value=['available','reserved','sold','inactive'].includes(i.status)?i.status:'available';d.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,st=f.querySelector('.save-status');st.textContent='Збереження…';const{error}=await supabase.rpc('seller_update_my_unit',{p_unit_id:i.id,p_price:Number(f.price.value),p_status:f.status.value,p_available_count:Number(f.count.value)});st.className='save-status '+(error?'error':'success');st.textContent=error?error.message:'Збережено ✓';if(!error)setTimeout(()=>Promise.all([loadSeller(),loadSellerStats()]),500)}}return d}
function leadCard(x){const d=document.createElement('article');d.className='lead-card';const contact=[x.phone?`<a href="tel:${x.phone}">${x.phone}</a>`:'',x.email?`<a href="mailto:${x.email}">${x.email}</a>`:''].filter(Boolean).join('');d.innerHTML=`<div class="lead-card-head"><div><h3>${x.customer_name||'Клієнт'}</h3><p>${x.unit_title||'Об’єкт'}${x.location_name?' · '+x.location_name:''}</p></div><span class="lead-badge status-${x.status}">${leadLabels[x.status]||x.status}</span></div><div class="lead-contact">${contact||'<span>Контакт не вказано</span>'}</div>${x.message?`<p class="lead-message">${x.message}</p>`:''}<div class="lead-card-foot"><time>${new Date(x.created_at).toLocaleString('uk-UA')}</time><select aria-label="Статус заявки">${Object.entries(leadLabels).map(([k,v])=>`<option value="${k}"${k===x.status?' selected':''}>${v}</option>`).join('')}</select></div>`;d.querySelector('select').onchange=async e=>{e.target.disabled=true;const{error}=await supabase.rpc('seller_update_lead_status',{p_lead_id:x.id,p_status:e.target.value});e.target.disabled=false;if(error){alert(error.message);e.target.value=x.status}else await loadLeads()};return d}
async function ensureProfile(){const{data,error}=await supabase.rpc('ensure_user_profile');if(error)throw error;return data}
async function load(){const{data:{session}}=await supabase.auth.getSession();$('authCard').hidden=!!session;$('cabinet').hidden=!session;if(!session)return;const profile=await ensureProfile();$('profileName').textContent=profile?.display_name||'Особистий кабінет';$('profileEmail').textContent=session.user.email||'';$('sellerRole').textContent=profile?.role==='seller'?'Продавець':'Покупець';await Promise.all([loadFavorites(),loadSeller(),loadSellerStats(),loadLeads()]);const token=new URLSearchParams(location.search).get('invite');if(token){$('inviteToken').value=token;activate('invite')}}
async function loadFavorites(){const{data:favs}=await supabase.from('user_favorites').select('unit_id').order('created_at',{ascending:false});const ids=(favs||[]).map(x=>x.unit_id);$('favoriteCount').textContent=ids.length;const grid=$('favoriteGrid');grid.replaceChildren();$('favoritesEmpty').hidden=ids.length>0;if(!ids.length)return;const{data:items}=await supabase.from('site_units').select('*').in('id',ids);(items||[]).forEach(i=>grid.append(card(i,'favorite')));grid.querySelectorAll('[data-remove]').forEach(b=>b.onclick=async()=>{await supabase.from('user_favorites').delete().eq('unit_id',b.dataset.remove);loadFavorites()})}
async function loadSellerStats(){const{data,error}=await supabase.rpc('seller_dashboard_stats');const v=error?{}:(data||{});$('sellerStatTotal').textContent=v.total||0;$('sellerStatAvailable').textContent=v.available||0;$('sellerStatReserved').textContent=v.reserved||0;$('sellerStatSold').textContent=v.sold||0;$('sellerStatFavorites').textContent=v.favorites||0}
async function loadSeller(){const{data,error}=await supabase.rpc('my_seller_units');const items=error?[]:(data||[]);$('sellerCount').textContent=items.length;const grid=$('sellerGrid');grid.replaceChildren();$('sellerEmpty').hidden=items.length>0;items.forEach(i=>grid.append(card(i,'seller')))}
function renderLeads(){const q=$('leadSearch').value.trim().toLowerCase(),select=$('leadStatusFilter').value;const filtered=leads.filter(x=>(leadFilter==='all'||x.status===leadFilter)&&(select==='all'||x.status===select)&&(!q||[x.customer_name,x.phone,x.email,x.unit_title,x.location_name].some(v=>String(v||'').toLowerCase().includes(q))));const list=$('leadList');list.replaceChildren();$('leadsEmpty').hidden=filtered.length>0;filtered.forEach(x=>list.append(leadCard(x)))}
function updateLeadSummary(){const count=status=>leads.filter(x=>status==='all'||x.status===status).length;$('leadAll').textContent=count('all');$('leadNew').textContent=count('new');$('leadContacted').textContent=count('contacted');$('leadViewing').textContent=count('viewing');$('leadNegotiation').textContent=count('negotiation');$('leadCount').textContent=count('new')}
async function loadLeads(){const{data,error}=await supabase.rpc('seller_my_leads');leads=error?[]:(data||[]);updateLeadSummary();renderLeads();if(error&&/permission|seller|role/i.test(error.message||''))$('leadsEmpty').textContent='Заявки доступні після підтвердження ролі продавця.'}
function activate(name){document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));$(name+'Panel').classList.add('active');if(name==='leads')loadLeads()}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>activate(b.dataset.tab));document.querySelectorAll('[data-lead-filter]').forEach(b=>b.onclick=()=>{leadFilter=b.dataset.leadFilter;document.querySelectorAll('[data-lead-filter]').forEach(x=>x.classList.toggle('active',x===b));renderLeads()});$('leadSearch').oninput=renderLeads;$('leadStatusFilter').onchange=renderLeads;$('refreshLeads').onclick=loadLeads;
$('loginForm').onsubmit=async e=>{e.preventDefault();const{error}=await supabase.auth.signInWithOtp({email:$('email').value.trim(),options:{emailRedirectTo:location.href}});$('authStatus').className=error?'error':'success';$('authStatus').textContent=error?error.message:'Посилання надіслано.'};$('logout').onclick=async()=>{await supabase.auth.signOut();location.reload()};$('inviteForm').onsubmit=async e=>{e.preventDefault();$('inviteStatus').textContent='Перевірка…';const{data,error}=await supabase.rpc('accept_seller_invite',{p_token:$('inviteToken').value.trim()});$('inviteStatus').className=error?'error':'success';$('inviteStatus').textContent=error?error.message:`Готово: прийнято ${data?.units||0} оголошень`;if(!error)await load()};supabase.auth.onAuthStateChange(load);load();