import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';
const supabase=createClient('https://vtnucevhyhfvymppjbfa.supabase.co','sb_publishable_-5iiF1Qgq--BKgXLHREINA_nPC7yVVY',{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id); const money=i=>i.price?new Intl.NumberFormat('uk-UA',{maximumFractionDigits:0}).format(i.price)+' '+({USD:'$',EUR:'€',UAH:'₴'}[i.currency]||i.currency||'$'):'Ціна уточнюється';
function card(i,mode){const d=document.createElement('article');d.className='card';const photo=i.cover_photo_url?`<img src="${i.cover_photo_url}" alt="">`:'<div class="placeholder">⌂</div>';d.innerHTML=`${photo}<div class="card-body"><h3>${i.title||i.location_name||'Будинок'}</h3><p>${i.location_name||''}${i.address?' · '+i.address:''}</p><p>${i.area_m2?i.area_m2+' м²':''}${i.land_area_sotka?' · '+i.land_area_sotka+' сот.':''}</p><div class="price">${money(i)}</div><div class="card-actions"><a href="./?unit=${i.id}">Відкрити</a>${mode==='favorite'?'<button data-remove="'+i.id+'">Видалити</button>':'<button disabled>Підтверджено</button>'}</div></div>`;return d}
async function ensureProfile(){const {data,error}=await supabase.rpc('ensure_user_profile');if(error)throw error;return data}
async function load(){const {data:{session}}=await supabase.auth.getSession();$('authCard').hidden=!!session;$('cabinet').hidden=!session;if(!session)return;const profile=await ensureProfile();$('profileName').textContent=profile?.display_name||'Особистий кабінет';$('profileEmail').textContent=session.user.email||'';$('sellerRole').textContent=profile?.role==='seller'?'Продавець':'Покупець';await Promise.all([loadFavorites(),loadSeller()]);const token=new URLSearchParams(location.search).get('invite');if(token){$('inviteToken').value=token;activate('invite')}}
async function loadFavorites(){const {data:favs}=await supabase.from('user_favorites').select('unit_id').order('created_at',{ascending:false});const ids=(favs||[]).map(x=>x.unit_id);$('favoriteCount').textContent=ids.length;const grid=$('favoriteGrid');grid.replaceChildren();$('favoritesEmpty').hidden=ids.length>0;if(!ids.length)return;const {data:items}=await supabase.from('site_units').select('*').in('id',ids);(items||[]).forEach(i=>grid.append(card(i,'favorite')));grid.querySelectorAll('[data-remove]').forEach(b=>b.onclick=async()=>{await supabase.from('user_favorites').delete().eq('unit_id',b.dataset.remove);loadFavorites()})}
async function loadSeller(){const {data,error}=await supabase.rpc('my_seller_units');const items=error?[]:(data||[]);$('sellerCount').textContent=items.length;const grid=$('sellerGrid');grid.replaceChildren();$('sellerEmpty').hidden=items.length>0;items.forEach(i=>grid.append(card(i,'seller')))}
function activate(name){document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));$(name+'Panel').classList.add('active')}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>activate(b.dataset.tab));$('loginForm').onsubmit=async e=>{e.preventDefault();$('authStatus').textContent='Надсилання…';const {error}=await supabase.auth.signInWithOtp({email:$('email').value.trim(),options:{emailRedirectTo:location.href}});$('authStatus').className=error?'error':'success';$('authStatus').textContent=error?error.message:'Посилання надіслано. Відкрийте email на цьому пристрої.'};$('logout').onclick=async()=>{await supabase.auth.signOut();location.reload()};$('inviteForm').onsubmit=async e=>{e.preventDefault();$('inviteStatus').textContent='Перевірка…';const {data,error}=await supabase.rpc('accept_seller_invite',{p_token:$('inviteToken').value.trim()});$('inviteStatus').className=error?'error':'success';$('inviteStatus').textContent=error?error.message:`Готово: прийнято ${data?.units||0} оголошень`;if(!error)await load()};supabase.auth.onAuthStateChange(()=>load());load();